name: 'Terraform Lambda Deployment'

on:
  push:
    branches: [ "main" ]

jobs:
  terraform-apply:

    name: 'Terraform Lambda Deployment'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - uses: actions/setup-node@v4
      name: Setup Node
      with:
        node-version: 18

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region:  ${{ vars.AWS_REGION }}
 
    - name: NPM Install
      run: npm ci --silent
      working-directory: ./lambda

    - name: TS/JS Transpilation
      run: tsc ./index.ts ./index.js
      continue-on-error: true
      working-directory: ./lambda

    - name: Moving Build Files
      run: |
        mv ./index.js ./build
        mv ./node_modules ./build
      working-directory: ./lambda

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve
